version: "3.8"

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
    - 5432:5432
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: suicidesquad1337/bot:latest
    volumes:
      - .:/usr/src/bot:ro
      - ./logs:/usr/src/bot/logs
    tty: true
    depends_on:
      - postgres
    environment:
      env_file: ".env"
