"""add basic database models

Revision ID: 791490d6dbc2
Revises: 
Create Date: 2020-12-05 16:10:05.815843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "791490d6dbc2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_integration",
        sa.Column("org_name", sa.String(), nullable=False),
        sa.Column("org_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "properties",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("org_name"),
        sa.UniqueConstraint("org_id"),
    )
    op.create_table(
        "owners",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("registered", sa.DateTime(), nullable=False),
        sa.Column("oauth_token_discord", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("discord_oauth_token", sa.String(), nullable=False),
        sa.Column("github_user_id", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "github_projects",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("org_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["github_integration.org_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "servers",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("owner", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner"],
            ["owners.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "autistenpunkte",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("member_id", sa.BigInteger(), nullable=False),
        sa.Column("server_id", sa.BigInteger(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("valid_after", sa.DateTime(), nullable=False),
        sa.Column("valid_until", sa.DateTime(), nullable=False),
        sa.Column("reason", sa.Unicode(), nullable=True),
        sa.Column(
            "reason_id",
            postgresql.ENUM("emoji_abuse", "spam", name="autistenpunktereason"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "server_properties",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("banned_emojis_raw", postgresql.ARRAY(sa.Unicode()), nullable=True),
        sa.Column(
            "banned_emojis_categories", postgresql.ARRAY(sa.Unicode()), nullable=True
        ),
        sa.Column(
            "banned_custom_emotes", postgresql.ARRAY(sa.Unicode()), nullable=True
        ),
        sa.Column(
            "banned_emojis_ignored_channels",
            postgresql.ARRAY(sa.BigInteger()),
            nullable=True,
        ),
        sa.Column("smaland_channel_id", sa.BigInteger(), nullable=False),
        sa.Column("smaland_max_autistenpunkte", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["servers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("server_properties")
    op.drop_table("autistenpunkte")
    op.drop_table("servers")
    op.drop_table("github_projects")
    op.drop_table("users")
    op.drop_table("owners")
    op.drop_table("github_integration")
    # ### end Alembic commands ###
