"""initial autistenpunkte table

Revision ID: 7be0683574ad
Revises: None
Create Date: 2020-11-15 15:49:30.546567

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7be0683574ad"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "autistenpunkte",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("autistenpunkte")
    # ### end Alembic commands ###
