"""initial oauth2 for discord

Revision ID: 946e5a58a65b
Revises: 7be0683574ad
Create Date: 2021-02-15 17:42:02.802426

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "946e5a58a65b"
down_revision = "7be0683574ad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth2_discord_entries",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("token_type", sa.String(), nullable=False),
        sa.Column("access_token", sa.String(), nullable=False),
        sa.Column("refresh_token", sa.String(), nullable=False),
        sa.Column("expires_at", sa.BigInteger(), nullable=False),
        sa.Column("scope", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("oauth2_discord_entries")
    # ### end Alembic commands ###
