"""add invite object

Revision ID: db7e361dc1da
Revises: 946e5a58a65b
Create Date: 2021-05-05 20:25:46.796387

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "db7e361dc1da"
down_revision = "946e5a58a65b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invited_members",
        sa.Column("member_id", sa.BigInteger(), nullable=False),
        sa.Column("inviter", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("member_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("invited_members")
    # ### end Alembic commands ###
