"""make invite code optional

Revision ID: fbbe33cc1e68
Revises: c6e80a722e8e
Create Date: 2021-06-06 01:49:17.464369

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fbbe33cc1e68"
down_revision = "c6e80a722e8e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invited_members", "invite", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invited_members", "invite", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
